# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import content_service_pb2 as content__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in content_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadTasks = channel.unary_unary(
                '/content_service.ContentService/LoadTasks',
                request_serializer=content__service__pb2.LoadTasksRequest.SerializeToString,
                response_deserializer=content__service__pb2.LoadTasksResponse.FromString,
                _registered_method=True)
        self.LoadProfile = channel.unary_unary(
                '/content_service.ContentService/LoadProfile',
                request_serializer=content__service__pb2.LoadProfileRequest.SerializeToString,
                response_deserializer=content__service__pb2.LoadProfileResponse.FromString,
                _registered_method=True)
        self.LoadComments = channel.unary_unary(
                '/content_service.ContentService/LoadComments',
                request_serializer=content__service__pb2.LoadCommentsRequest.SerializeToString,
                response_deserializer=content__service__pb2.LoadCommentsResponse.FromString,
                _registered_method=True)
        self.LoadSubmissionStatus = channel.unary_unary(
                '/content_service.ContentService/LoadSubmissionStatus',
                request_serializer=content__service__pb2.LoadSubmissionStatusRequest.SerializeToString,
                response_deserializer=content__service__pb2.LoadSubmissionStatusResponse.FromString,
                _registered_method=True)


class ContentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def LoadTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadSubmissionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadTasks,
                    request_deserializer=content__service__pb2.LoadTasksRequest.FromString,
                    response_serializer=content__service__pb2.LoadTasksResponse.SerializeToString,
            ),
            'LoadProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadProfile,
                    request_deserializer=content__service__pb2.LoadProfileRequest.FromString,
                    response_serializer=content__service__pb2.LoadProfileResponse.SerializeToString,
            ),
            'LoadComments': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadComments,
                    request_deserializer=content__service__pb2.LoadCommentsRequest.FromString,
                    response_serializer=content__service__pb2.LoadCommentsResponse.SerializeToString,
            ),
            'LoadSubmissionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadSubmissionStatus,
                    request_deserializer=content__service__pb2.LoadSubmissionStatusRequest.FromString,
                    response_serializer=content__service__pb2.LoadSubmissionStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'content_service.ContentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('content_service.ContentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content_service.ContentService/LoadTasks',
            content__service__pb2.LoadTasksRequest.SerializeToString,
            content__service__pb2.LoadTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content_service.ContentService/LoadProfile',
            content__service__pb2.LoadProfileRequest.SerializeToString,
            content__service__pb2.LoadProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content_service.ContentService/LoadComments',
            content__service__pb2.LoadCommentsRequest.SerializeToString,
            content__service__pb2.LoadCommentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadSubmissionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/content_service.ContentService/LoadSubmissionStatus',
            content__service__pb2.LoadSubmissionStatusRequest.SerializeToString,
            content__service__pb2.LoadSubmissionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
