# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sso.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sso.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsso.proto\x12\x03sso\"@\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"\"\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\".\n\x0cLoginRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\".\n\rLoginResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"%\n\x14TokenValidateRequest\x12\r\n\x05token\x18\x01 \x01(\t\"k\n\x15TokenValidateResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\x12\x0f\n\x07isModer\x18\x02 \x01(\x08\x12\x0e\n\x06userId\x18\x03 \x01(\x03\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t2\xbd\x01\n\nssoService\x12\x37\n\x08Register\x12\x14.sso.RegisterRequest\x1a\x15.sso.RegisterResponse\x12.\n\x05Login\x12\x11.sso.LoginRequest\x1a\x12.sso.LoginResponse\x12\x46\n\rTokenValidate\x12\x19.sso.TokenValidateRequest\x1a\x1a.sso.TokenValidateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sso_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=18
  _globals['_REGISTERREQUEST']._serialized_end=82
  _globals['_REGISTERRESPONSE']._serialized_start=84
  _globals['_REGISTERRESPONSE']._serialized_end=118
  _globals['_LOGINREQUEST']._serialized_start=120
  _globals['_LOGINREQUEST']._serialized_end=166
  _globals['_LOGINRESPONSE']._serialized_start=168
  _globals['_LOGINRESPONSE']._serialized_end=214
  _globals['_TOKENVALIDATEREQUEST']._serialized_start=216
  _globals['_TOKENVALIDATEREQUEST']._serialized_end=253
  _globals['_TOKENVALIDATERESPONSE']._serialized_start=255
  _globals['_TOKENVALIDATERESPONSE']._serialized_end=362
  _globals['_SSOSERVICE']._serialized_start=365
  _globals['_SSOSERVICE']._serialized_end=554
# @@protoc_insertion_point(module_scope)
