# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'task_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12task_service.proto\x12\x0ctask_service\"L\n\x08TestCase\x12\x14\n\x0cwanted_input\x18\x01 \x01(\t\x12\x15\n\rwanted_output\x18\x02 \x01(\t\x12\x13\n\x0bmax_time_ms\x18\x03 \x01(\x05\"\x97\x01\n\x11\x43reateTaskRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tdifficult\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12*\n\ntest_cases\x18\x06 \x03(\x0b\x32\x16.task_service.TestCase\"$\n\x12\x43reateTaskResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"G\n\x15SubmitSolutionRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\"(\n\x16SubmitSolutionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xbb\x01\n\x0bTaskService\x12O\n\nCreateTask\x12\x1f.task_service.CreateTaskRequest\x1a .task_service.CreateTaskResponse\x12[\n\x0eSubmitSolution\x12#.task_service.SubmitSolutionRequest\x1a$.task_service.SubmitSolutionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTCASE']._serialized_start=36
  _globals['_TESTCASE']._serialized_end=112
  _globals['_CREATETASKREQUEST']._serialized_start=115
  _globals['_CREATETASKREQUEST']._serialized_end=266
  _globals['_CREATETASKRESPONSE']._serialized_start=268
  _globals['_CREATETASKRESPONSE']._serialized_end=304
  _globals['_SUBMITSOLUTIONREQUEST']._serialized_start=306
  _globals['_SUBMITSOLUTIONREQUEST']._serialized_end=377
  _globals['_SUBMITSOLUTIONRESPONSE']._serialized_start=379
  _globals['_SUBMITSOLUTIONRESPONSE']._serialized_end=419
  _globals['_TASKSERVICE']._serialized_start=422
  _globals['_TASKSERVICE']._serialized_end=609
# @@protoc_insertion_point(module_scope)
